[package]
name = "iw"
version = "0.1.0"
authors = ["neikos"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_assertions = "1.1.0"
libc = "0.2.66"
thiserror = "1.0.9"

[build-dependencies]
bindgen = "0.52.0"
